num1=input("Enter the binary number 1=")
num2=input("Enter the binary number 2=")
sum=bin(int(num1,2)+int(num2,2))
print("Sum of binary numbers: ",sum[2:])
num3=input("Enter the binary number 3=")
num4=input("Enter the binary number 4=")
sum=bin(int(num3,4)+int(num4,4))
print("Sum of binary numbers: ",sum[2:])